2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_setup.py:_flush():67] Configure stats pid to 289519
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_setup.py:_flush():67] Loading settings from /home/nasir-hussain/.config/wandb/settings
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_setup.py:_flush():67] Loading settings from /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/settings
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/run-20250416_010558-sqhl7naz/logs/debug.log
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/run-20250416_010558-sqhl7naz/logs/debug-internal.log
2025-04-16 01:05:58,728 INFO    MainThread:289519 [wandb_init.py:init():781] calling init triggers
2025-04-16 01:05:58,729 INFO    MainThread:289519 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-16 01:05:58,729 INFO    MainThread:289519 [wandb_init.py:init():809] starting backend
2025-04-16 01:05:58,729 INFO    MainThread:289519 [wandb_init.py:init():813] sending inform_init request
2025-04-16 01:05:58,738 INFO    MainThread:289519 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-16 01:05:58,738 INFO    MainThread:289519 [wandb_init.py:init():823] backend started and connected
2025-04-16 01:05:58,739 INFO    MainThread:289519 [wandb_init.py:init():915] updated telemetry
2025-04-16 01:05:58,745 INFO    MainThread:289519 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-16 01:05:59,781 INFO    MainThread:289519 [wandb_init.py:init():1014] starting run threads in backend
2025-04-16 01:06:00,041 INFO    MainThread:289519 [wandb_run.py:_console_start():2454] atexit reg
2025-04-16 01:06:00,042 INFO    MainThread:289519 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-16 01:06:00,042 INFO    MainThread:289519 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-16 01:06:00,043 INFO    MainThread:289519 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-16 01:06:00,045 INFO    MainThread:289519 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-16 01:06:14,075 INFO    MsgRouterThr:289519 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-16 01:07:15,743 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,748 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,749 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,750 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,752 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,754 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,755 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,756 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,757 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,758 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,759 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,760 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,761 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,762 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,762 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,763 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,764 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,765 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,766 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,766 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,767 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,767 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,768 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,768 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,768 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,770 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,770 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,771 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,771 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,772 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,773 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:07:15,773 ERROR   MainThread:289519 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
