2025-04-16 01:03:24,406 INFO    MainThread:289363 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-16 01:03:24,407 INFO    MainThread:289363 [wandb_setup.py:_flush():67] Configure stats pid to 289363
2025-04-16 01:03:24,407 INFO    MainThread:289363 [wandb_setup.py:_flush():67] Loading settings from /home/nasir-hussain/.config/wandb/settings
2025-04-16 01:03:24,408 INFO    MainThread:289363 [wandb_setup.py:_flush():67] Loading settings from /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/settings
2025-04-16 01:03:24,408 INFO    MainThread:289363 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-16 01:03:24,408 INFO    MainThread:289363 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/run-20250416_010324-fs3u8jmz/logs/debug.log
2025-04-16 01:03:24,409 INFO    MainThread:289363 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/wandb/run-20250416_010324-fs3u8jmz/logs/debug-internal.log
2025-04-16 01:03:24,409 INFO    MainThread:289363 [wandb_init.py:init():781] calling init triggers
2025-04-16 01:03:24,410 INFO    MainThread:289363 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-16 01:03:24,410 INFO    MainThread:289363 [wandb_init.py:init():809] starting backend
2025-04-16 01:03:24,411 INFO    MainThread:289363 [wandb_init.py:init():813] sending inform_init request
2025-04-16 01:03:24,433 INFO    MainThread:289363 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-16 01:03:24,435 INFO    MainThread:289363 [wandb_init.py:init():823] backend started and connected
2025-04-16 01:03:24,441 INFO    MainThread:289363 [wandb_init.py:init():915] updated telemetry
2025-04-16 01:03:24,470 INFO    MainThread:289363 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-16 01:03:57,675 INFO    MainThread:289363 [wandb_init.py:init():1014] starting run threads in backend
2025-04-16 01:03:57,960 INFO    MainThread:289363 [wandb_run.py:_console_start():2454] atexit reg
2025-04-16 01:03:57,961 INFO    MainThread:289363 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-16 01:03:57,962 INFO    MainThread:289363 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-16 01:03:57,962 INFO    MainThread:289363 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-16 01:03:57,966 INFO    MainThread:289363 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-16 01:03:58,354 INFO    MsgRouterThr:289363 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-16 01:04:21,786 INFO    Thread-3 (wrapped_target):289363 [retry.py:__call__():175] [no run ID] Retry attempt failed:
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7c31ac25b370>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c31ac25b370>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 134, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 402, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c31ac25b370>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2025-04-16 01:05:31,841 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,844 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,844 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,845 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,845 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,845 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,846 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,846 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,847 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,847 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,848 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,848 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,848 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,849 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,849 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,850 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,850 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,851 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,853 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,854 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,854 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,855 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,856 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,856 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,857 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,857 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,859 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,859 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,860 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,861 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,861 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,862 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-16 01:05:31,862 ERROR   MainThread:289363 [redirect.py:_on_write():661] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nasir-hussain/Pictures/Depression_Detection_Using_Machine_Learning/env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
